version: '3.8'

services:
  cosmos-node:
    image: cosmos-sdk:latest # Соберём кастомный образ ниже
    build:
      context: .
      dockerfile: docker/cosmos.Dockerfile
    ports:
      - "26656:26656" # P2P
      - "26657:26657" # RPC
      - "1317:1317"   # REST API
      - "9090:9090"   # gRPC
    volumes:
      - cosmos-data:/root/.simapp
    command: ["start"]
    environment:
      - CHAIN_ID=my-test-chain

volumes:
  cosmos-data:
